ARG BASE_CONTAINER=yikunkero/spark:latest

FROM $BASE_CONTAINER as spark

LABEL maintainer="Andrew Bauman"

FROM spark as delta

USER root

ARG DELTA_CORE_VERSION="2.1.0"

RUN pip install --no-cache-dir delta-spark==${DELTA_CORE_VERSION} \
jupyterlab deltalake pandas roapi

FROM delta as startup

ARG NBuser=NBuser
ARG GROUP=NBuser
ARG WORKDIR=/opt/spark/work-dir
ENV DELTA_PACKAGE_VERSION=delta-core_2.12:2.1.0

RUN groupadd -r ${GROUP} && useradd -r -m -g ${GROUP} ${NBuser}
RUN apt-get update
RUN apt-get -y install vim

COPY --chown=${NBuser} startup.sh "${WORKDIR}"
COPY --chown=${NBuser} quickstart.ipynb "${WORKDIR}"
COPY --chown=${NBuser} rs/ "${WORKDIR}/rs"
RUN chown -R ${NBuser}:${GROUP} /home/${NBuser}/ \
&& chown -R ${NBuser}:${GROUP} ${WORKDIR}

USER ${NBuser}

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENTRYPOINT ["bash", "startup.sh"]