[[plugins]]
package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/*"
  to = "https://d1urk4s4laun85.cloudfront.net/:splat"
  status = 200

# [[redirects]]
#   from = "/2.1.0/*"
#   to = "https://d1urk4s4laun85.cloudfront.net/2.1.0/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/2.0.1/*"
#   to = "https://d1urk4s4laun85.cloudfront.net/2.0.1/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/2.0.0/*"
#   to = "https://d1urk4s4laun85.cloudfront.net/2.0.0/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/1.2.1/*"
#   to = "https://d1urk4s4laun85.cloudfront.net/1.2.1/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/1.2.0/*"
#   to = "https://d1urk4s4laun85.cloudfront.net/1.2.0/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/1.0.1/*"
#   to = "https://d1urk4s4laun85.cloudfront.net/1.0.1/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/1.0.0/*"
#   to = "https://d1urk4s4laun85.cloudfront.net/1.0.0/:splat"
#   status = 200
#   force = true
  
# [[redirects]]
#   from = "/0.8.0/*"
#   to = "https://d1urk4s4laun85.cloudfront.net/0.8.0/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/0.7.0/*"
#   to = "https://d1urk4s4laun85.cloudfront.net/0.7.0/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/0.6.1/*"
#   to = "https://d1urk4s4laun85.cloudfront.net/0.6.1/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/0.6.0/*"
#   to = "https://d1urk4s4laun85.cloudfront.net/0.6.0/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/0.5.0/*"
#   to = "https://d1urk4s4laun85.cloudfront.net/0.5.0/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/0.4.0/*"
#   to = "https://d1urk4s4laun85.cloudfront.net/0.4.0/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/0.3.0/*"
#   to = "https://d1urk4s4laun85.cloudfront.net/0.3.0/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/0.2.0/*"
#   to = "https://d1urk4s4laun85.cloudfront.net/0.2.0/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/0.0.1/*"
#   to = "https://d1urk4s4laun85.cloudfront.net/0.0.1/:splat"
#   status = 200
#   force = true